/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.FileWriter;
import java.io.PrintWriter;

public class AppTest {
    @Test public void FileExists() {
        CountWords classUnderTest = new CountWords();
        assertEquals(classUnderTest.checkIfFileExists("C:\\Windows\\system.ini"), true,"the file exists");
    }
    
    @Test public void FileNotExist() {
        CountWords classUnderTest = new CountWords();
        assertEquals(classUnderTest.checkIfFileExists("bla-bla_"+ System.currentTimeMillis()+".ini"), false,"the file doesn't exist");
    }
    
    @Test public void ifCountsProperly(){
    	File f1 = new File("bin/TestFile_TestNG_"+ System.currentTimeMillis()+".txt");	
    	try {
    		      
    		f1.createNewFile();	
    		FileWriter fw = new FileWriter(f1);
			PrintWriter out = new PrintWriter(fw);  
		    out.println("word1 word2 word3");  
		    out.close();  
    	}
		catch (IOException e) { e.printStackTrace();}
    	
	   	System.setIn(new ByteArrayInputStream(f1.getPath().getBytes()));
		CountWords classUnderTest = new CountWords();
		String nameGiven = classUnderTest.askUserForAFilePath();
		assertEquals(classUnderTest.CountWords(nameGiven), 3,"Counts properly");
	}
}
